### ISSUE TITLE
CSS incomplete

### ISSUE THREAD

**Issue by DOCUTEE** [mely-apps/melyoj#14]
![image](https://github.com/mely-apps/melyoj/assets/110187691/57f5e711-26e0-47f4-a789-a55340993839)
choose Region, Font color is same with Background color
![image](https://github.com/mely-apps/melyoj/assets/110187691/bfcf6869-1987-4d78-8bfe-0fb0d4756c39)
CSS MORE AND MOREEE

**Comment by Hi1805** [comment]
![image](https://github.com/mely-apps/melyoj/assets/59696851/c559281a-8498-4195-bf1d-d6fcf70552c3)
Đã fixed
