### ISSUE TITLE
Not show current code when refresh page

### ISSUE THREAD

**Issue by DOCUTEE** [mely-apps/melyoj#18]
https://github.com/mely-apps/melyoj/assets/110187691/1c47e725-3c6a-473a-9e3e-b2163da659b5

**Comment by Hi1805** [comment]
@emladevops em check xem nhé

**Comment by emladevops** [comment]
Anh để ý phần URL nha, nó là resubmit code cho submission id 19, nếu muốn resubmit thì cần ấn Resubmit trong trang hiện kết quả.

<img width="1800" alt="Screenshot 2024-04-30 at 17 53 49" src="https://github.com/mely-apps/melyoj/assets/80335335/036fffee-29cf-4e0c-99e3-d3992328d4a9">

**Comment by Hi1805** [comment]
fixed
