### ISSUE TITLE
Select2 width issue

### ISSUE THREAD

**Issue by emladevops** [mely-apps/melyoj#23]
During the rendering process, this might happen: 
![image](https://github.com/mely-apps/melyoj/assets/80335335/5f08e766-7f46-4f52-b8ef-220485294e5d)

The page itself was intended to look like so:
![image](https://github.com/mely-apps/melyoj/assets/80335335/d54b4971-eb69-4451-876d-35d377d6316e)

**Comment by Hi1805** [comment]
https://github.com/mely-apps/melyoj/pull/26

Done
