### ISSUE TITLE
Thạng thái bài tập không cập nhật

### ISSUE THREAD

**Issue by nyagami** [mely-apps/melyoj#31]
### What happened?

Trạng thái bài tập không được cập nhật
Không hẳn là bug, do bên DMOJ cache request nên phải đợi ngày hôm sau nó mới update 

![image](https://github.com/mely-apps/SudoMeLy/assets/86464880/4bcdc209-752c-4ddd-9aa9-8d8da0d2eddb)
![image](https://github.com/mely-apps/SudoMeLy/assets/86464880/3713a5ca-d0d0-4c13-8414-32092cda4742)

### Reproduction

1. Chọn 1 bài chưa submit.
2. Submit AC
3. Check lại bài đó ở dánh sách bài tập
4. Trạng thái vẫn là chưa nộp

**Comment by emladevops** [comment]
@Hi1805 anh cân nhắc tắt cache của cloudflare nha anh :v

**Comment by nyagami** [comment]
K phải đâu, DMOJ họ cache request này ấy

**Comment by emladevops** [comment]
> K phải đâu, DMOJ họ cache request này ấy

Em đang k nhìn được ảnh mẫu...
![image](https://github.com/mely-apps/melyoj/assets/80335335/7db98486-6785-43ab-9ec0-9eb47e5598f4)

**Comment by nyagami** [comment]
![image](https://github.com/mely-apps/melyoj/assets/86464880/126a90e7-44aa-40f7-a5d2-879567057177)
![image](https://github.com/mely-apps/melyoj/assets/86464880/76679c16-39ac-4ee6-93eb-19dcfbece573)

**Comment by emladevops** [comment]
Duplicate of #16

**Comment by emladevops** [comment]
> ![image](https://github.com/mely-apps/melyoj/assets/86464880/126a90e7-44aa-40f7-a5d2-879567057177)
> 
> ![image](https://github.com/mely-apps/melyoj/assets/86464880/76679c16-39ac-4ee6-93eb-19dcfbece573)
> 
> 
> 
> 

Anh thử nhấn Ctrl+F5 xem có thay đổi gì không nhé.

**Comment by nyagami** [comment]
Như a bảo, DMOJ họ cache phía server. Nên k reload lại dcđâu
![image](https://github.com/mely-apps/melyoj/assets/86464880/edde3770-ab0e-4cea-9ab5-a0086a8888b5)

**Comment by emladevops** [comment]
> Như a bảo, DMOJ họ cache phía server. Nên k reload lại dcđâu ![image](https://private-user-images.githubusercontent.com/86464880/332374583-edde3770-ab0e-4cea-9ab5-a0086a8888b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyODYyNDgsIm5iZiI6MTcxNjI4NTk0OCwicGF0aCI6Ii84NjQ2NDg4MC8zMzIzNzQ1ODMtZWRkZTM3NzAtYWIwZS00Y2VhLTlhYjUtYTAwODZhODg4OGI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDEwMDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4ODY4MTcwMjc4ZTc0Mzg4YWY2ZWExOTEzOTRiNDE1MGNmZTIxZTg5M2U3ZTZkNTI5YzJkMzk0YzM3OThhNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dLGxSpUpIu3ZluGAZswl0OlRT5aMnVMxsYhVb-cVV6E)

btw, trang này được render dựa trên ssr, nên sẽ k có yêu cầu fetch gửi // nhận.

**Comment by nyagami** [comment]
ý a là a disable cache phía client (dev tool). Nên chắc chắn cache từ phía server.
Trước a có đọc qua đoạn code này 1 lần r

**Comment by emladevops** [comment]
Trang này được render tại line 379-393

```python
# judge/views/problem.py

            elif sort_key == 'solved':
                if self.request.user.is_authenticated:
                    profile = self.request.profile
                    solved = user_completed_ids(profile)
                    attempted = user_attempted_ids(profile)

                    def _solved_sort_order(problem):
                        if problem.id in solved:
                            return 1
                        if problem.id in attempted:
                            return 0
                        return -1

                    queryset = list(queryset)
                    queryset.sort(key=_solved_sort_order, reverse=self.order.startswith('-'))
```

**Comment by emladevops** [comment]
Cần test lại trong thời gian 1 tuần trước khi close issue.

**Comment by emladevops** [comment]
Everything is working perfectly, closing the issue rn.
